### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by andreustimm** [eduardolundgren/trackingjs.com#11]
Como andam os novos recursos traking.js, existe um cronograma de lançamento ou de desenvolvimento? Gostaria de ajudar, só não sei ainda como...

**Comment by eduardolundgren** [comment]
Hello Andre, I am answering in english in order to allow other contributors to follow the thread.

I am pushing soon a branch with a new tracker engine based on keypoints that will allow track bounding boxes in a scene without an artificial marker. I am struggling with Clamp8Array performance still.

When it's pushed I will leave a comment in this thread, feel free to play with it and send pull requests.

**Comment by zenorocha** [comment]
This repository scope is related to the tracking.js website, not the library. Please create an issue on [tracking.js](https://github.com/eduardolundgren/tracking.js)
